Repository codeit15-2-2/fandom-k, pull requests merged in 2025-04, with the labels that each got.

#7 refactor: 프로젝트 설정 재초기화 (WIP)
  .github/ISSUE_TEMPLATE/bug-template.md
  package.json
  pnpm-lock.yaml
  src/apis/chartsApi.js
  src/apis/donationsApi.js
  src/apis/idolApi.js
  src/apis/idolsApi.js
  src/apis/imageApi.js
  src/apis/instance.js
  src/apis/voteApi.js
  src/apis/votesApi.js
  src/configs/apiConfig.js
  src/constants/apiConstants.js
  src/constants/endpoints.js
  src/constants/errorMessages.js
  src/contexts/dummy
  src/hooks/dummy
  src/index.css
  src/mocks/dummy
  src/services/dummy
  src/utils/apiUtils.js
  src/utils/dummy
  src/utils/parseError.js
  tsconfig-none.jsonf
Labels: 🛠️ refactor, ⚙️ setting

#13 [setting] 코어 타임 프로젝트 세팅 구조 수정
  src/App.jsx
  src/layouts/GlobalLayout.jsx
  src/main.jsx
  src/routes/index.jsx
Labels: ⚙️ setting

#21 #8 공통 컴포넌트 (아이돌 리스트)
  src/assets/icons/dummy
  src/assets/icons/icon_checked.jsx
  src/components/common/ProfileImg.jsx
  src/components/common/dummy
  src/components/vote/IdolList.jsx
  src/components/vote/Selected.jsx
Labels: 🧩 feature

#23 Feat/20 아이돌 리스트 선택 탭 컴포넌트
  src/pages/main-page/components/Idol-list-tab-content.jsx
  src/pages/main-page/components/Idol-list-tab.jsx
  src/pages/main-page/index.jsx
  src/pages/main-page/pages/Content.jsx
  src/routes/index.jsx
Labels: 🎨 design, 🧩 feature

#30 Feat/29 마이 크레딧 컴포넌트
  src/assets/icons/icon_jewel.jsx
  src/pages/main-page/components/MyCredit.jsx
  src/pages/main-page/index.jsx
Labels: 🎨 design

#28 Feat/24 헤더 디자인 구현
  src/assets/images/dummy
  src/assets/images/img_empty-profile.webp
  src/assets/images/img_fandom-k-logo.webp
  src/components/layouts/Header.jsx
Labels: 🎨 design

#25 Feat/19 인풋공통컴포넌트 & 크레딧인풋관련 컴포넌트
  src/assets/icons/icon_Credit.jsx
  src/components/common/Input.jsx
  src/components/credit-form/CreditController.jsx
  src/components/credit-form/CreditForm.jsx
  src/hooks/useCreditForm.jsx
  src/utils/validateInput.js
Labels: 🎨 design, 🧩 feature

#26 #22 공통 컴포넌트 (아바타 프로필)
  src/assets/icons/icon_remove.jsx
  src/components/common/ProfileImg.jsx
  src/components/common/SelectedLayer.jsx
  src/components/favorites/AvatarProfile.jsx
  src/components/favorites/RemoveButton.jsx
  src/components/vote/IdolList.jsx
Labels: 🎨 design, 🧩 feature

#17 Feat/9 공통 컴포넌트 - 버튼
  src/assets/icons/icon_spinner.jsx
  src/components/common/Button.jsx
  src/constants/buttonConstants.js
Labels: 🧩 feature

#27 #11 공통 컴포넌트 (카드 프로필)
  src/assets/icons/icon_credit.jsx
  src/components/card/IdolCard.jsx
  src/components/common/CardImg.jsx
Labels: 🎨 design

#37 Bug/icon credit
  src/assets/icons/icon_credit.jsx
Labels: 🐞 bug

#38 Develop 브랜치 내용을 Main 브랜치에 최신화
  .github/worklflows/deploy.yml
  build.sh
  src/assets/icons/dummy
  src/assets/icons/icon_Credit.jsx
  src/assets/icons/icon_checked.jsx
  src/assets/icons/icon_credit.jsx
  src/assets/icons/icon_jewel.jsx
  src/assets/icons/icon_remove.jsx
  src/assets/icons/icon_spinner.jsx
  src/assets/images/dummy
  src/assets/images/img_empty-profile.webp
  src/assets/images/img_fandom-k-logo.webp
  src/components/card/IdolCard.jsx
  src/components/common/Button.jsx
  src/components/common/CardImg.jsx
  src/components/common/Input.jsx
  src/components/common/Modal.jsx
  src/components/common/ProfileImg.jsx
  src/components/common/SelectedLayer.jsx
  src/components/common/dummy
  src/components/credit-form/CreditController.jsx
  src/components/credit-form/CreditForm.jsx
  src/components/favorites/AvatarProfile.jsx
  src/components/favorites/RemoveButton.jsx
  src/components/layouts/Header.jsx
  src/components/vote/IdolList.jsx
  src/constants/buttonConstants.js
  src/hooks/dummy
  src/hooks/useCreditForm.jsx
  src/hooks/useModal.jsx
  src/pages/main-page/components/Idol-list-tab-content.jsx
  src/pages/main-page/components/Idol-list-tab.jsx
  src/pages/main-page/components/MyCredit.jsx
  src/pages/main-page/index.jsx
  src/pages/main-page/pages/Content.jsx
  src/routes/index.jsx
  src/utils/validateInput.js
Labels: 🌐 deploy

#40 chore: vercel.json 파일 추가
  vercel.json
Labels: 🐞 bug, 🧩 feature

#43 Feat/41 버튼 컴포넌트 리팩토링
  src/components/common/Button.jsx
  src/constants/buttonConstants.js
Labels: 🛠️ refactor

#51 #48 후원 제목 컴포넌트 (후원 상세 페이지)
  src/pages/detail-page/components/DetailTitle.jsx
  src/pages/detail-page/components/MainTitle.jsx
Labels: 🎨 design

#47 #42 후원 정보 컴포넌트 (후원 상세 페이지)
  src/components/DonationInfo.jsx
  src/constants/donationConstants.js
  src/hooks/useCountdownTimer.js
  src/hooks/useWebWorkerTimer.js
  src/libs/timerWorker.js
  src/utils/donationInfoUtils.js
Labels: 🎨 design, 🧩 feature

#55 Feat/45 메인 페이지 캐러셀 영역 구현
  src/apis/donateApi.js
  src/apis/instance.js
  src/components/card/IdolCard.jsx
  src/components/common/Carousel.jsx
  src/constants/buttonConstants.js
  src/pages/detail-page/components/DetailTitle.jsx
  src/pages/detail-page/components/MainTitle.jsx
  src/pages/main-page/index.jsx
  src/pages/main-page/sections/DonateCarousel.jsx
Labels: 🎨 design, 🧩 feature

#60 breakpoint가 적용안되는 버그 수정 및 안쓰는 변수 삭제
  src/index.css
Labels: 🐞 bug

#57 Feat/33 마이페이지 1차구현
  src/apis/instance.js
  src/assets/icons/icon_spinner.jsx
  src/components/credit-form/CreditForm.jsx
  src/hooks/useWindowSize.jsx
  src/index.css
  src/pages/my-page/components/FavoriteIdolList.jsx
  src/pages/my-page/components/MiddleDivider.jsx
  src/pages/my-page/components/SelectIdolList.jsx
  src/pages/my-page/hooks/useMyPageIdols.jsx
  src/pages/my-page/index.jsx
  src/utils/storeFavorite.js
Labels: 🎨 design, 🧩 feature

#68 Feat/58 메인 페이지 구현 (1차)
  src/components/common/Carousel.jsx
  src/components/common/Modal.jsx
  src/hooks/useCredit.js
  src/pages/main-page/components/CreditModal.jsx
  src/pages/main-page/components/MyCredit.jsx
  src/pages/main-page/index.jsx
  src/pages/main-page/sections/DonateCarousel.jsx
Labels: 🎨 design

#67 #66 카드 프로필 기능 추가(목표 금액 대비 퍼센트 및 D-Day 계산 기능 구현)
  src/components/card/IdolCard.jsx
  src/utils/donationCardUtils.js
Labels: 🧩 feature

#69 Feat/64 반응형 캐러셀 구현 및 캐러셀이 동작하지 않는 버그 수정
  src/apis/donateApi.js
  src/components/common/Carousel.jsx
  src/hooks/useCarousel.jsx
  src/pages/main-page/index.jsx
Labels: 🐞 bug, 🧩 feature

#63 #62 DonateModal에 Api연결
  src/apis/ContributeApi.js
  src/assets/icons/icon_credit.jsx
  src/pages/detail-page/DonateModal.jsx
Labels: 📮 api

#77 #59 랜딩페이지 반응형 레이아웃 구현
  src/assets/elements/elem_handphone_mobile.png
  src/assets/elements/elem_handphone_tablet.png
  src/index.css
  src/pages/landing-page/components/common/Button.jsx
  src/pages/landing-page/components/common/DarkLayout.jsx
  src/pages/landing-page/components/elements/Circle.jsx
  src/pages/landing-page/components/elements/FundingCard.jsx
  src/pages/landing-page/components/elements/wrist-band/SecurityCut.jsx
  src/pages/landing-page/components/elements/wrist-band/Triangle.jsx
  src/pages/landing-page/components/elements/wrist-band/WristBand.jsx
  src/pages/landing-page/constants/layouts.js
  src/pages/landing-page/index.jsx
  src/pages/landing-page/sections/ChartSection.jsx
  src/pages/landing-page/sections/CreditSection.jsx
  src/pages/landing-page/sections/DonationSection.jsx
  src/pages/landing-page/sections/FundingSection.jsx
  src/pages/landing-page/sections/HeroSection.jsx
  src/pages/landing-page/sections/HorizontalDonationSection.jsx
  src/pages/landing-page/sections/VerticalDonationSection.jsx
Labels: 🎨 design

#78 #56 후원 상세 페이지 적응형 디자인 (PC, Tablet, Mobile)
  src/App.jsx
  src/components/layouts/Header.jsx
  src/constants/buttonConstants.js
  src/constants/donationConstants.js
  src/hooks/useDeviceSize.js
  src/hooks/useElementHeight.js
  src/hooks/useScrollAnimation.js
  src/pages/detail-page/components/BackgroundIdolImage.jsx
  src/pages/detail-page/components/DetailContent.jsx
  src/pages/detail-page/components/DetailTitle.jsx
  src/pages/detail-page/components/DonationInfo.jsx
  src/pages/detail-page/components/MainTitle.jsx
  src/pages/detail-page/index.jsx
  src/pages/detail-page/sections/mobile/DetailSection.jsx
  src/pages/detail-page/sections/mobile/MainSection.jsx
  src/pages/detail-page/sections/pc/MainSection.jsx
  src/pages/detail-page/sections/tablet/MainSection.jsx
Labels: 🎨 design

#82 Feat/72 메인 페이지 구현 (2차)
  .github/workflows/deploy.yml
  src/components/card/IdolCard.jsx
  src/components/common/Carousel.jsx
  src/components/credit-form/CreditForm.jsx
  src/components/layouts/Header.jsx
  src/hooks/useCarousel.jsx
  src/hooks/useCredit.js
  src/hooks/useCredit.jsx
  src/pages/detail-page/index.jsx
  src/pages/main-page/components/CreaditModal.jsx
  src/pages/main-page/components/CreditModal.jsx
  src/pages/main-page/components/MonthlyChartHeader.jsx
  src/pages/main-page/components/MonthlyChartTabs.jsx
  src/pages/main-page/components/MyCredit.jsx
  src/pages/main-page/index.jsx
  src/pages/main-page/sections/DonateCarousel.jsx
  src/pages/main-page/sections/MonthlyChartSection.jsx
  src/pages/my-page/index.jsx
Labels: 🎨 design, 🧩 feature

#89 #85 후원 상세 페이지 데이터 연결
  src/mocks/donationDetailData.json
  src/mocks/dummy
  src/pages/detail-page/components/DetailContent.jsx
  src/pages/detail-page/components/DonateModal.jsx
  src/pages/detail-page/components/DonationInfo.jsx
  src/pages/detail-page/index.jsx
  src/pages/detail-page/sections/mobile/DetailSection.jsx
  src/pages/detail-page/sections/mobile/MainSection.jsx
  src/pages/detail-page/sections/pc/MainSection.jsx
  src/pages/detail-page/sections/tablet/MainSection.jsx
Labels: 🎨 design, 🧩 feature, 📮 api

#91 #74 랜딩페이지 애니메이션 구현
  src/assets/avatars/avatar-1.webp
  src/assets/avatars/avatar-2.webp
  src/assets/avatars/avatar-3.webp
  src/assets/avatars/avatar-4.webp
  src/assets/avatars/avatar-5.webp
  src/assets/avatars/avatar-6.webp
  src/assets/avatars/avatar-7.webp
  src/assets/doodles/arrow-black.png
  src/assets/doodles/arrow-pink.webp
  src/assets/doodles/spark-coral.png
  src/assets/doodles/spark-orange.png
  src/assets/doodles/spark-yellow.webp
  src/assets/elements/elem_handphone.webp
  src/assets/elements/elem_handphone_mobile.webp
  src/assets/elements/elem_handphone_tablet.webp
  src/assets/logos/logo-stroked.webp
  src/assets/logos/logo.webp
  src/pages/landing-page/hooks/useObserver.js
  src/pages/landing-page/sections/ChartSection.jsx
  src/pages/landing-page/sections/CreditSection.jsx
  src/pages/landing-page/sections/FundingSection.jsx
  src/pages/landing-page/sections/HeroSection.jsx
  src/pages/landing-page/sections/HorizontalDonationSection.jsx
  src/pages/landing-page/sections/VerticalDonationSection.jsx
  src/pages/landing-page/utils/getIdolAvatar.js
Labels: 🎨 design, 🧩 feature

#88 Feat/71 마이페이지 반응형 수정/ 애니메이션 추가
  src/components/credit-form/CreditForm.jsx
  src/index.css
  src/pages/my-page/components/FavoriteIdolList.jsx
  src/pages/my-page/components/MiddleDivider.jsx
  src/pages/my-page/components/SelectIdolList.jsx
  src/pages/my-page/components/common/Button.jsx
  src/pages/my-page/hooks/useFavoriteHandler.jsx
  src/pages/my-page/hooks/useInfiniteScroll.jsx
  src/pages/my-page/hooks/useMyPageIdols.jsx
  src/pages/my-page/index.jsx
  src/pages/my-page/sections/FavoriteListSection.jsx
  src/pages/my-page/sections/SelectListSection.jsx
Labels: 🎨 design, 🛠️ refactor

#93 #81 투표하기 모달창 구현
  src/components/common/Modal.jsx
  src/pages/main-page/components/MonthlyChartHeader.jsx
  src/pages/main-page/components/VoteIdolList.jsx
  src/pages/main-page/components/VoteModal.jsx
  src/pages/main-page/components/VoteModalFooter.jsx
  src/pages/main-page/index.jsx
  src/pages/main-page/sections/MonthlyChartSection.jsx
Labels: 🧩 feature

#90 Feat/86 메인 페이지 리팩토링
  src/assets/icons/icon_chevron-left.jsx
  src/assets/icons/icon_chevron-right.jsx
  src/assets/icons/icon_plus.jsx
  src/components/common/Carousel.jsx
  src/components/layouts/Header.jsx
  src/pages/main-page/components/MonthlyChartContent.jsx
  src/pages/main-page/components/MonthlyChartList.jsx
  src/pages/main-page/components/MyCredit.jsx
  src/pages/main-page/index.jsx
  src/pages/main-page/sections/DonateCarousel.jsx
Labels: 🛠️ refactor

#96 #95 feat: conflict merge 중 삭제를 잘못하여 난 충돌 해결
  src/pages/main-page/index.jsx
Labels: 🐞 bug

#107 #105 not found page 디자인
  src/pages/detail-page/index.jsx
  src/pages/not-found-page/index.jsx
  src/routes/index.jsx
Labels: 🎨 design

#103 #100 후원 상세페이지의 크레딧 오류 및 리팩토링
  src/components/credit-form/CreditForm.jsx
  src/components/layouts/Header.jsx
  src/contexts/DonationContext.jsx
  src/contexts/dummy
  src/mocks/donationDetailData.json
  src/pages/detail-page/components/DonateModal.jsx
  src/pages/detail-page/index.jsx
  src/pages/detail-page/sections/mobile/MainSection.jsx
  src/pages/detail-page/sections/pc/MainSection.jsx
  src/pages/detail-page/sections/tablet/MainSection.jsx
  src/pages/main-page/sections/DonateCarousel.jsx
  src/routes/index.jsx
Labels: 🐞 bug, 🛠️ refactor

#109 #104 후원 상세 페이지 렌더링 오류 & 성능 개선
  index.html
  src/contexts/DonationContext.jsx
  src/index.css
  src/pages/detail-page/components/DetailContent.jsx
  src/pages/detail-page/components/DetailTitle.jsx
  src/pages/detail-page/components/MainTitle.jsx
  src/pages/detail-page/index.jsx
  tailwind.config.js
Labels: 🐞 bug, 🛠️ refactor

#111 #110 useCredit에서의 CreditContext import명수정
  src/hooks/useCredit.js
Labels: 🐞 bug

#113 #99 main 페이지 이동 시 localStorage 초기화
  src/pages/landing-page/components/common/Button.jsx
  src/pages/landing-page/sections/CreditSection.jsx
  src/pages/landing-page/sections/HeroSection.jsx
  tailwind.config.js
Labels: 🛠️ refactor

#114 #112 refactor(CreditContext):App.jsx 에서의 import명수정
  src/App.jsx
Labels: 🐞 bug

#119 Feat/117 MyPage 세부 리팩토링
  src/hooks/useWindowSize.jsx
  src/index.css
  src/pages/my-page/components/FavoriteIdolList.jsx
  src/pages/my-page/components/SelectIdolList.jsx
  src/pages/my-page/components/common/Button.jsx
  src/pages/my-page/hooks/useFavoriteHandler.js
  src/pages/my-page/hooks/useInfiniteScroll.js
  src/pages/my-page/hooks/useMyPageIdols.js
  src/pages/my-page/hooks/usePreventScrollBar.js
  src/pages/my-page/index.jsx
  src/pages/my-page/sections/SelectListSection.jsx
Labels: 🛠️ refactor

#120 feat/116 Toast 구현
  package.json
  pnpm-lock.yaml
  src/App.jsx
  src/components/common/Toast.jsx
  src/components/layouts/Header.jsx
  src/contexts/ToastContext.jsx
  src/pages/detail-page/components/DonateModal.jsx
  src/pages/main-page/components/VoteModal.jsx
  src/pages/my-page/hooks/useFavoriteHandler.js
Labels: 🎨 design, 🧩 feature

#124 #123 Toast 컴포넌트 중복 style 제거
  src/components/common/Toast.jsx
Labels: 🐞 bug

#127 Feat/121 CreditFoem/마이페이지 QA 개선사항 수정
  src/apis/ContributeApi.js
  src/components/common/Input.jsx
  src/components/credit-form/CreditController.jsx
  src/components/credit-form/CreditForm.jsx
  src/contexts/CreditContext.jsx
  src/hooks/useCreditForm.js
  src/pages/detail-page/components/DonateModal.jsx
  src/pages/my-page/components/FavoriteIdolList.jsx
  src/pages/my-page/components/SelectIdolList.jsx
  src/pages/my-page/sections/FavoriteListSection.jsx
  src/utils/validateInput.js
Labels: 🛠️ refactor

#126 #118 메인페이지 리팩토링
  src/components/card/IdolCard.jsx
  src/components/common/Carousel.jsx
  src/components/common/Modal.jsx
  src/components/layouts/Header.jsx
  src/constants/buttonConstants.js
  src/hooks/useCarousel.js
  src/pages/main-page/components/ChartErrorMessage.jsx
  src/pages/main-page/components/CreditModal.jsx
  src/pages/main-page/sections/DonateCarousel.jsx
  src/pages/main-page/sections/MonthlyChartSection.jsx
Labels: 🛠️ refactor

#130 #115 후원 상세 페이지 리팩토링
  src/assets/icons/icon_scroll-up-arrow.jsx
  src/hooks/useElementHeight.js
  src/hooks/useScrollAnimation.js
  src/pages/detail-page/components/MainTitle.jsx
  src/pages/detail-page/components/ViewDetailButton.jsx
  src/pages/detail-page/index.jsx
  src/pages/detail-page/sections/mobile/DetailSection.jsx
  src/pages/detail-page/sections/mobile/MainSection.jsx
  src/pages/detail-page/sections/pc/MainSection.jsx
  src/pages/detail-page/sections/tablet/MainSection.jsx
Labels: 🛠️ refactor

#133 #125 Toast 리팩토링 외 Layout 수정 및 구현
  src/App.jsx
  src/assets/icons/icon_github.jsx
  src/components/common/Toast.jsx
  src/components/layouts/Footer.jsx
  src/pages/detail-page/components/DonateModal.jsx
  src/pages/main-page/index.jsx
  src/pages/my-page/components/common/Button.jsx
  src/pages/my-page/index.jsx
  src/pages/my-page/sections/SelectListSection.jsx
Labels: 🛠️ refactor

#134 #132 아이돌 리스트 투표형에 label 적용
  src/components/vote/IdolList.jsx
Labels: 🛠️ refactor

#135 #131 mock 데이터 수정
  src/mocks/donationDetailData.json
Labels: 💬 chore

#122 [#108] 이달의 차트 및 투표 모달 리팩토링
  src/apis/ contributeApi.js
  src/assets/icons/icon_chart.jsx
  src/components/common/Modal.jsx
  src/components/common/ProfileImg.jsx
  src/contexts/ChartContext.jsx
  src/hooks/useChartPagination.js
  src/pages/main-page/components/MonthlyChartContent.jsx
  src/pages/main-page/components/VoteIdolList.jsx
  src/pages/main-page/components/VoteModal.jsx
  src/pages/main-page/components/VoteModalFooter.jsx
  src/pages/main-page/index.jsx
Labels: 🛠️ refactor

#139 [#138] 파일명 앞에 공백 수정
  src/apis/contributeApi.js
Labels: 🐞 bug

#141 [#140] ChartProvider 누락으로 추가
  src/pages/main-page/index.jsx
Labels: 🐞 bug

#144 #143 refactor(Project):QA사항 수정
  src/App.jsx
  src/components/common/Toast.jsx
  src/pages/main-page/components/VoteModal.jsx
  src/pages/main-page/sections/DonateCarousel.jsx
  src/pages/my-page/components/SelectIdolList.jsx
  src/routes/index.jsx
  src/utils/validateInput.js
Labels: 🛠️ refactor

#146 [#145] fix: 투표 후 모달 데이터 동기화 및 크레딧 부족 판정 오류 수정
  src/pages/main-page/components/VoteModal.jsx
Labels: 🐞 bug

#152 #151 feat:리드미 수정
  README.md
Labels: 💬 chore
